import { defineField, defineType } from 'sanity'

export const siteSettingsType = defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  groups: [
    { name: 'marquee',    title: 'Marquee Ticker' },
    { name: 'hero',       title: 'Hero Section' },
    { name: 'featured',   title: 'Featured Collection' },
    { name: 'newArrivals',title: 'New Arrivals' },
    { name: 'philosophy', title: 'Philosophy / Story' },
    { name: 'values',     title: 'Values Grid' },
    { name: 'bespoke',    title: 'Bespoke Section' },
    { name: 'editorial',  title: 'Editorial Quote' },
    { name: 'ctaBand',    title: 'CTA Band' },
    { name: 'trustBadges',title: 'Trust Badges' },
    { name: 'aboutPage',  title: 'About Page' },
    { name: 'contact',    title: 'Contact Settings' },
  ],
  fields: [

    // ── MARQUEE ──────────────────────────────────────────────────────────────
    defineField({
      name: 'marqueeItems',
      title: 'Marquee Messages',
      type: 'array',
      group: 'marquee',
      description: 'Scrolling messages in the gold ticker bar at the top. Min 3, max unlimited.',
      of: [{ type: 'string', validation: (R) => R.required().min(3) }],
      initialValue: [
        'Premium Handcrafted Dimensional Wood Relief',
        'Hand-painted with protective PU coat',
        'Complimentary shipping across India',
      ],
      validation: (R) => R.required().min(3),
    }),

    // ── HERO ─────────────────────────────────────────────────────────────────
    defineField({
      name: 'heroHeadlinePre',
      title: 'Hero Headline — Line 1',
      type: 'string',
      group: 'hero',
      description: 'First line of the large hero headline.',
      initialValue: 'Objects of',
      validation: (R) => R.required().min(2).max(60),
    }),
    defineField({
      name: 'heroHeadlineAccent',
      title: 'Hero Headline — Accent word (italic gold)',
      type: 'string',
      group: 'hero',
      description: 'This single word appears in italic gold in the headline.',
      initialValue: 'quiet',
      validation: (R) => R.required().min(2).max(30),
    }),
    defineField({
      name: 'heroHeadlinePost',
      title: 'Hero Headline — Line 3',
      type: 'string',
      group: 'hero',
      description: 'Third line of the headline (usually ends with a full stop).',
      initialValue: 'conviction.',
      validation: (R) => R.required().min(2).max(60),
    }),
    defineField({
      name: 'heroDescription',
      title: 'Hero Description',
      type: 'text',
      rows: 3,
      group: 'hero',
      description: 'Paragraph below the headline on the right side.',
      initialValue: 'Premium handcrafted dimensional wood relief art — each piece is individually hand-finished with a protective PU coat and curated to bring a lasting, quiet presence to refined spaces.',
      validation: (R) => R.required().min(20).max(300),
    }),
    defineField({
      name: 'heroSubNote',
      title: 'Hero Sub-note',
      type: 'string',
      group: 'hero',
      description: 'Small monospace text below the description.',
      initialValue: '15 ready designs · custom wall art available',
      validation: (R) => R.required().min(5).max(80),
    }),

    // ── FEATURED ─────────────────────────────────────────────────────────────
    defineField({
      name: 'featuredEyebrow',
      title: 'Featured — Eyebrow Label',
      type: 'string',
      group: 'featured',
      description: 'Small uppercase label above the section heading.',
      initialValue: 'Featured · Selection Nº 04',
      validation: (R) => R.required().min(3).max(60),
    }),
    defineField({
      name: 'featuredHeadlinePre',
      title: 'Featured — Heading (before accent)',
      type: 'string',
      group: 'featured',
      initialValue: 'A collection curated',
      validation: (R) => R.required().min(2).max(80),
    }),
    defineField({
      name: 'featuredHeadlineAccent',
      title: 'Featured — Heading accent word (italic gold)',
      type: 'string',
      group: 'featured',
      initialValue: 'notice',
      validation: (R) => R.required().min(2).max(30),
    }),
    defineField({
      name: 'featuredHeadlinePost',
      title: 'Featured — Heading (after accent)',
      type: 'string',
      group: 'featured',
      description: 'Punctuation or continuation after the gold accent word.',
      initialValue: '.',
      validation: (R) => R.required().max(40),
    }),
    defineField({
      name: 'featuredProducts',
      title: 'Featured Products Selection',
      type: 'array',
      group: 'featured',
      description: 'Select exactly 5 products and drag them to arrange their layout order on the homepage (1st: Left-large, 2nd: Middle, 3rd: Right-small, 4th & 5th: Bottom row).',
      of: [{ type: 'reference', to: [{ type: 'product' }] }],
      initialValue: [
        { _key: 'fp1', _ref: 'product_wanxmf05', _type: 'reference' },
        { _key: 'fp2', _ref: 'product_wmnxmf22', _type: 'reference' },
        { _key: 'fp3', _ref: 'product_wmnxmf27_sq', _type: 'reference' },
        { _key: 'fp4', _ref: 'product_wmnxmf39', _type: 'reference' },
        { _key: 'fp5', _ref: 'product_winxmf01', _type: 'reference' },
      ],
      validation: (R) => R.required().min(5).max(5),
    }),

    // ── NEW ARRIVALS ──────────────────────────────────────────────────────────
    defineField({
      name: 'newArrivalsEyebrow',
      title: 'New Arrivals — Eyebrow Label',
      type: 'string',
      group: 'newArrivals',
      initialValue: 'Just in · New arrivals',
      validation: (R) => R.required().min(3).max(60),
    }),
    defineField({
      name: 'newArrivalsHeadlinePre',
      title: 'New Arrivals — Heading (before accent)',
      type: 'string',
      group: 'newArrivals',
      initialValue: 'Recently added',
      validation: (R) => R.required().min(2).max(80),
    }),
    defineField({
      name: 'newArrivalsHeadlineAccent',
      title: 'New Arrivals — Heading accent word (italic gold)',
      type: 'string',
      group: 'newArrivals',
      initialValue: 'catalogue',
      validation: (R) => R.required().min(2).max(30),
    }),
    defineField({
      name: 'newArrivalsHeadlinePost',
      title: 'New Arrivals — Heading (after accent)',
      type: 'string',
      group: 'newArrivals',
      initialValue: '.',
      validation: (R) => R.required().max(40),
    }),

    // ── PHILOSOPHY ───────────────────────────────────────────────────────────
    defineField({
      name: 'philosophyEyebrow',
      title: 'Philosophy — Eyebrow Label',
      type: 'string',
      group: 'philosophy',
      initialValue: 'Atelier · Our philosophy',
      validation: (R) => R.required().min(3).max(60),
    }),
    defineField({
      name: 'philosophyHeadingPre',
      title: 'Philosophy — Heading (before accent)',
      type: 'string',
      group: 'philosophy',
      initialValue: "We don't create",
      validation: (R) => R.required().min(2).max(80),
    }),
    defineField({
      name: 'philosophyHeadingAccent',
      title: 'Philosophy — Heading accent word (italic gold)',
      type: 'string',
      group: 'philosophy',
      initialValue: 'décor',
      validation: (R) => R.required().min(2).max(30),
    }),
    defineField({
      name: 'philosophyHeadingPost',
      title: 'Philosophy — Heading (after accent)',
      type: 'string',
      group: 'philosophy',
      initialValue: 'We create presence.',
      validation: (R) => R.required().min(2).max(80),
    }),
    defineField({
      name: 'philosophyBody',
      title: 'Philosophy — Body Paragraphs',
      type: 'array',
      group: 'philosophy',
      description: 'Each item = one paragraph. Min 1, max 6 paragraphs.',
      of: [{ type: 'text' }],
      initialValue: [
        'Wallantq is a collection of considered moments — the rhythm, depth, and quiet power a wall can hold. Each piece is crafted layer by layer, shaped by intention, to become a part of a space that speaks.',
        "We don't follow trends; we follow meaning.",
        'There is no mass production, no shortcuts, just craftsmanship, patience, and purpose. If a piece connects with you, it belongs in your story.',
      ],
      validation: (R) => R.required().min(1).max(6),
    }),
    defineField({
      name: 'philosophyAttribution',
      title: 'Philosophy — Attribution',
      type: 'string',
      group: 'philosophy',
      description: 'Line below the paragraphs (italic style).',
      initialValue: '— the founder',
      validation: (R) => R.required().min(2).max(60),
    }),

    // ── VALUES GRID ───────────────────────────────────────────────────────────
    defineField({
      name: 'values',
      title: 'Values',
      type: 'array',
      group: 'values',
      description: 'Min 1, max 4 value cards shown in a grid.',
      of: [
        defineField({
          name: 'value',
          title: 'Value',
          type: 'object',
          fields: [
            defineField({ name: 'num',   title: 'Number (e.g. Nº 01)', type: 'string', validation: (R) => R.required().max(10) }),
            defineField({ name: 'title', title: 'Title',               type: 'string', validation: (R) => R.required().min(3).max(60) }),
            defineField({ name: 'body',  title: 'Body',                type: 'text', rows: 3, validation: (R) => R.required().min(10).max(300) }),
          ],
          preview: { select: { title: 'title', subtitle: 'num' } },
        }),
      ],
      initialValue: [
        { num: 'Nº 01', title: 'Dimensional Wood Relief',   body: 'Each piece is built from individually hand-cut and layered wood elements, hand-painted with a protective PU coat. No shortcuts, no mass production.' },
        { num: 'Nº 02', title: 'Private enquiry',           body: 'No cart, no checkout. Write to us on WhatsApp or email and receive a personal reply within 24 hours.' },
        { num: 'Nº 03', title: 'Your vision, our creation', body: 'Every design is fully customizable — size, palette, finish — crafted to fit your space and your story.' },
        { num: 'Nº 04', title: '7-day guarantee',           body: 'Not satisfied? Return within 7 days, no questions asked. Every piece ships with a hand-written card and care instructions.' },
      ],
      validation: (R) => R.required().min(1).max(4),
    }),

    // ── BESPOKE ───────────────────────────────────────────────────────────────
    defineField({
      name: 'bespokeEyebrow',
      title: 'Bespoke — Eyebrow Label',
      type: 'string',
      group: 'bespoke',
      initialValue: 'Bespoke · Personalised designs',
      validation: (R) => R.required().min(3).max(60),
    }),
    defineField({
      name: 'bespokeHeadlinePre',
      title: 'Bespoke — Heading line 1',
      type: 'string',
      group: 'bespoke',
      initialValue: 'Your wall.',
      validation: (R) => R.required().min(2).max(60),
    }),
    defineField({
      name: 'bespokeHeadlineAccent',
      title: 'Bespoke — Heading accent word (italic gold)',
      type: 'string',
      group: 'bespoke',
      initialValue: 'vision',
      validation: (R) => R.required().min(2).max(30),
    }),
    defineField({
      name: 'bespokeHeadlinePost',
      title: 'Bespoke — Heading line 3',
      type: 'string',
      group: 'bespoke',
      initialValue: 'Our craft.',
      validation: (R) => R.required().min(2).max(60),
    }),
    defineField({
      name: 'bespokeBody1',
      title: 'Bespoke — Body paragraph 1',
      type: 'text',
      rows: 3,
      group: 'bespoke',
      initialValue: "We create fully personalised wall art — commissioned to fit your space, your palette, and your story. Whether it's a mandala for a meditation room, a family heritage piece, or an abstract for a corporate lobby, every design begins with a conversation.",
      validation: (R) => R.required().min(20).max(400),
    }),
    defineField({
      name: 'bespokeBody2',
      title: 'Bespoke — Body paragraph 2',
      type: 'text',
      rows: 2,
      group: 'bespoke',
      initialValue: 'No templates. No stock. Just the piece that belongs in your home.',
      validation: (R) => R.required().min(10).max(200),
    }),

    // ── EDITORIAL QUOTE ───────────────────────────────────────────────────────
    defineField({
      name: 'editorialQuotePre',
      title: 'Editorial Quote — Text before accent',
      type: 'text',
      rows: 2,
      group: 'editorial',
      description: 'Text that appears before the gold accent word.',
      initialValue: 'The most important things in a room are the ones that make you',
      validation: (R) => R.required().min(10).max(200),
    }),
    defineField({
      name: 'editorialQuoteAccent',
      title: 'Editorial Quote — Accent word (italic gold)',
      type: 'string',
      group: 'editorial',
      initialValue: 'pause',
      validation: (R) => R.required().min(2).max(30),
    }),

    // ── CTA BAND ─────────────────────────────────────────────────────────────
    defineField({
      name: 'ctaEyebrow',
      title: 'CTA Band — Eyebrow Label',
      type: 'string',
      group: 'ctaBand',
      initialValue: 'A private line',
      validation: (R) => R.required().min(3).max(60),
    }),
    defineField({
      name: 'ctaHeadingPre',
      title: 'CTA Band — Heading line 1',
      type: 'string',
      group: 'ctaBand',
      initialValue: 'Looking for something',
      validation: (R) => R.required().min(3).max(80),
    }),
    defineField({
      name: 'ctaHeadingPost',
      title: 'CTA Band — Heading line 2',
      type: 'string',
      group: 'ctaBand',
      initialValue: 'in particular?',
      validation: (R) => R.required().min(3).max(80),
    }),
    defineField({
      name: 'ctaBody',
      title: 'CTA Band — Body paragraph',
      type: 'text',
      rows: 3,
      group: 'ctaBand',
      initialValue: "Describe what you're searching for — a particular tone, a size for a narrow wall, a piece for a quiet hallway — and we'll return with hand-picked suggestions within 24 hours.",
      validation: (R) => R.required().min(20).max(400),
    }),

    // ── TRUST BADGES ─────────────────────────────────────────────────────────
    defineField({
      name: 'trustBadges',
      title: 'Trust Badges',
      type: 'array',
      group: 'trustBadges',
      description: 'Min 1, max 4 badges. Icons are fixed in code; only the text is editable.',
      of: [
        defineField({
          name: 'badge',
          title: 'Badge',
          type: 'object',
          fields: [
            defineField({ name: 'title', title: 'Title',    type: 'string', validation: (R) => R.required().min(2).max(50) }),
            defineField({ name: 'sub',   title: 'Subtitle', type: 'string', validation: (R) => R.required().min(2).max(60) }),
          ],
          preview: { select: { title: 'title', subtitle: 'sub' } },
        }),
      ],
      initialValue: [
        { title: 'Free Shipping',             sub: 'Complimentary within India' },
        { title: '7 Day Guarantee',           sub: 'Money back, no questions' },
        { title: 'Your Vision, Our Creation', sub: 'Fully customizable' },
        { title: '100% Secure',               sub: 'Private & secure enquiry' },
      ],
      validation: (R) => R.required().min(1).max(4),
    }),

    // ── ABOUT PAGE IMAGES ────────────────────────────────────────────────────
    defineField({
      name: 'aboutHeroImage',
      title: 'About Us — Hero Image',
      type: 'image',
      group: 'aboutPage',
      options: { hotspot: true },
    }),
    defineField({
      name: 'aboutMissionImage',
      title: 'About Us — Mission Image',
      type: 'image',
      group: 'aboutPage',
      options: { hotspot: true },
    }),
    defineField({
      name: 'aboutStudioImage',
      title: 'About Us — Studio Image',
      type: 'image',
      group: 'aboutPage',
      options: { hotspot: true },
    }),
    // ── CONTACT ──────────────────────────────────────────────────────────────
    defineField({
      name: 'contactEmail',
      title: 'Contact Email',
      type: 'string',
      group: 'contact',
      placeholder: 'info@wallantq.com',
      initialValue: 'info@wallantq.com',
      validation: (R) => R.email(),
    }),
    defineField({
      name: 'contactPhone',
      title: 'Contact Phone / WhatsApp (with country code, e.g. +91 63537 26302)',
      type: 'string',
      group: 'contact',
      placeholder: '+91 63537 26302',
      initialValue: '+91 63537 26302',
    }),
  ],
})
